### PR TITLE
Prod publication

### PR DESCRIPTION
**Pull request by 3manuek**
### Description
Publishing changes to prod
 
### Issues Resolved
[List any issues this PR will resolve]

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

### CODE REVIEW

**Review by AMoo-Miki — APPROVED** [review]
LGTM. Thanks.

**Review by lgarciaog — APPROVED** [review]

**Comment by nasbyj** [comment]
Please update with the CI commit that just hit `main`.

**Review by 3manuek — COMMENTED** [review]
@gopinathpai By enabling the DCO, is it required to do sign-off commits? We have prod pushes blocked as of now we don't have sign-off enabled in the main branch. 
cc/ @nasbyj

**Comment by nasbyj** [comment]
I think we need different rules for `prod` vs `main`; namely we shouldn't require `--signoff` for commits into prod, because when we squash merge into `main` we're not doing signoff (nor should we AFAIK).

**Comment by AMoo-Miki** [comment]
> I think we need different rules for `prod` vs `main`; namely we shouldn't require `--signoff` for commits into prod, because when we squash merge into `main` we're not doing signoff (nor should we AFAIK).

We should never squash since it rewrites history.

**Review by AMoo-Miki — APPROVED** [review]

**Review by xaviersierra — APPROVED** [review]

**Pull request merged**
