### PR TITLE
Change title and content of vision file to purpose

### PR DESCRIPTION
**Pull request by renee2468**
Remove marketing aspect, tighten up description and change "vision" to "purpose"

### CODE REVIEW

**Review by 3manuek — DISMISSED** [review]

**Comment by 3manuek** [comment]
@renee2468 @postgresql007 This requires review extra review.

**Comment by gopinathpai** [comment]
@renee2468 @postgresql007 - As discussed in the standup today, please review this again.

**Review by nasbyj — CHANGES_REQUESTED** [review]
We need to understand where these changes are coming from.

**Comment by laurenz** [comment]
@nasbyj This is mostly a rename from `vision.md` to `purpose.md`, because &ldquo;vision&rdquo; sounded too &ndash; well &ndash; visionary.
As far as I understand, the text changes are supposed to make the text sound more sober.

**Comment by laurenz** [comment]
I need a verdict here: should the rename of the page be undone or not?
I don't care either way, just tell me what to do.

**Review by renee2468 — COMMENTED** [review]
As far as I can see, the changes I made have been accepted... @nasbyj is there any further action I need to take on this? I see the problem with renaming the file-- the diff is just gone.

**Comment by gopinathpai** [comment]
@renee2468 - as discussed please use the content from the AWS documentation here.

**Comment by laurenz** [comment]
@gopinathpai Some information must have gone missing: Which page from the AWS documentation are you referring to?

**Comment by susanmdouglas-aws** [comment]
I think this is the Introductory content that Gopi is referring to - it's the introduction to the Babelfish project from the AWS guide (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish.html):

Babelfish for Aurora PostgreSQL extends your Amazon Aurora PostgreSQL-Compatible Edition database with the ability to accept database connections from Microsoft SQL Server clients. This allows applications originally built for SQL Server to work directly with Aurora PostgreSQL with few code changes compared to a traditional migration and without changing database drivers. 

Babelfish provides an additional endpoint for an Aurora PostgreSQL database cluster that allows it to understand the SQL Server wire-level protocol and commonly used SQL Server statements. This approach allows client applications that use the Tabular Data Stream (TDS) wire protocol to connect natively to the TDS listener port on Aurora PostgreSQL. Babelfish supports TDS versions 7.1 and higher. 

You can access your data simultaneously using a Babelfish TDS connection from one application and a native PostgreSQL connection from another application. You can customize the ports used for each client connection when you create the cluster, or later in your Aurora PostgreSQL parameter group. By default, to use the following dialects, use the following ports:

SQL Server dialect, clients connect to port 1433.

PostgreSQL dialect, clients connect to port 5432.

Babelfish runs the Transact-SQL (T-SQL) language with the exceptions documented in Differences between Aurora PostgreSQL with Babelfish and SQL Server.

**Comment by laurenz** [comment]
Copied the Aurora documentation in 122234402105953c7943fc206daec5a19ba2594f.

**Comment by laurenz** [comment]
I reinstated the "contributing" section.

**Review by susanmdouglas-aws — APPROVED** [review]

**Comment by 3manuek** [comment]
Hi @renee2468, could you please get the commits signed-off so the DCO check pass?

@nasbyj @rcv-aws Could you review please this PR?

**Comment by laurenz** [comment]
Please review and merge #137 instead.

**Pull request closed without merging**
